### ISSUE TITLE
[Suggestion]Vex riding vanilla bat

### ISSUE THREAD

**Issue by supersaiyansubtlety** [ACGaming/Jockeys#1]
A vex or another small mob riding a vanilla bat could be fun. Or maybe instead of a true vanilla bat it'd be better to extend the vanilla bat so you can give it unique AI and spawning conditions, but w/e works.

**Comment by ACGaming** [comment]
Done! I decided to base the bat AI itself on vexes, so that they can hunt players through walls. Because of this, they are a more rare variant as well.

**Comment by supersaiyansubtlety** [comment]
Thanks!
